import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Bjj Calendar v1",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <main className="mx-auto flex h-screen items-center justify-center">
      {children}
    </main>
  );
}
